config/routes.rb
Rails.application.routes.draw do

  get 'transactions/create'
  get 'transactions/destroy'
  get 'transactions/update'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'accounts#show'

  resources :budgets,          only: [:show, :index] do
    resources :accounts,       only: [:show, :create, :update] do
      resources :transactions, only: [:create, :update]
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :budget
  has_many :transactions
  validates :name, presence: true, length: { maximum: 32 }



  def total
    transactions.sum(:amount_in) - transactions.sum(:amount_out)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :accounts
  validates :name, presence: true, length: { maximum: 32 }

  def total
    sum = 0
    accounts.each { |account| sum += account.total }
    return sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions
  validates :name, presence: true
end

app/models/payee.rb
class Payee < ApplicationRecord
  belongs_to :user
  has_many :transactions
  validates :name, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :payee
  belongs_to :category
  validates :transaction_date, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save { email.downcase! }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


  has_many :budgets
  has_many :payees
  has_many :categories


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def show
    @budget = current_budget
    @accounts = @budget.accounts
    @account = current_account
    @transactions = @account.transactions
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def current_budget
    unless params[:id].nil?
      @budget = current_user.budgets.find(params[:id])
    else
      @budget = current_user.budgets.first
    end
  end

  def current_account
    unless params[:id].nil?
      @account = current_budget.accounts.find(params[:id])
    else
      @budget = current_budget.accounts.first
    end
  end

  protected
    def authenticate_user!
      if user_signed_in?
        super
      else
        redirect_to user_session_path
      end
    end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

  before_action :authenticate_user!

  def show
    current_budget
    @accounts = @budget.accounts
  end

  def index
    @budgets = current_user.budgets
  end


end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
    category = Category.find_by(name: params[:transaction][:category])
    payee = Payee.find_by(name: params[:transaction][:payee])
    payee ||= current_user.payees.build(name: params[:transaction][:payee])

    @transaction = current_account.transactions.build(
        transaction_date: params[:transaction][:transaction_date],
        payee: payee,
        category: category,
        amount_in: params[:transaction][:amount_in],
        amount_out: params[:transaction][:amount_out]
      )

    if @transaction.save
      @account = current_account
      @transactions = current_account.transactions
      notice = "Transaction saved"
      respond_to do |format|
        format.js { render :layout => !request.xhr? }
      end
    else
      notice = "Transaction could not be saved"
    end

  end

  def destroy
  end

  def update
  end


  private
    def transaction_params
      params.require(:transaction).permit(:transaction_date, :payee,
                                          :category, :amount_in, :amount_out)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_account.html.erb
<div class="account-name">
<%= link_to account.name, budget_account_path(budget_id: account.budget.id, id: account.id) %>
</div>
<div class="account-total">
<%= account.total %>
</div>
<div class="clear"></div>

app/views/accounts/_transaction_table.html.erb
<table id="transaction-container">
  <tr>
  <th>Date</th>
  <th>Payee</th>
  <th>Category</th>
  <th>Amount In</th>
  <th>Amount Out</th>
  </tr>
  <%= render @transactions %>
<tr>
<%= form_with model: Transaction.new, url: budget_account_transactions_path(budget_id: @account.budget.id, account_id: @account.id), remote: true, html: { class: "transaction" } do |f| %>
</td>
<td>
<%= f.date_field :transaction_date, placeholder: "#{Date.today()}" %>
</td>
<td>
<%= f.text_field :payee, placeholder: "Payee" %>
</td>
<td>
<%= f.select :category, options_for_select(current_user.categories.map { |c| c.name }) %>
</td>
<td>
<%= f .number_field :amount_in %>
</td>
<td>
<%= f.number_field :amount_out %>
</td>
<td>
<%= f.button "√", type: :submit %>
</td>
<td>
<%= f.button "X", type: :reset %>
</td>
</tr>
</table>
<% end %>

app/views/accounts/index.html.erb
<%= render @accounts %>

app/views/accounts/show.html.erb
<div id="transaction-table-container">
<%= render 'transaction_table' %>
</div>

app/views/budgets/index.html.erb
<h1>Budgets#index</h1>
<p>Find me in app/views/budgets/index.html.erb</p>

app/views/budgets/show.html.erb
<%= render @accounts %>

app/views/layouts/_footer.html.erb
<footer>
Some footer text
  </footer>

app/views/layouts/_header.html.erb
<header>

  <% unless current_user.nil? %>
    <%= current_user.email %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <% end %>
    

<%= link_to "Logout", "#" %>



</header>

app/views/layouts/_sidebar.html.erb
<section id="sidebar">

  <div class="sidebar-content">
    <ul>
      <li>
        Accounts
      </li>
      <li>
        Budget
      </li>
      <li>
        Reports
      </li>
    </ul>
  </div>

    <% unless @accounts.nil? %>
<div id="account-container" class="sidebar-content">

<%= render @accounts %>


<div class="account-name">Total:</div>
<div class="account-total">
  <%= @budget.total %>
  </div>
<div class="clear"></div>
<div id="new-account">
<%= link_to "New Account", "#" %>
</div>
</div>
<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectPlutus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="grid-container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/sidebar' %>
      <section id="content">
    <p class="notice" id="notice"><%= notice %></p>
    <p class="alert" id="alert"><%= alert %></p>
    <%= yield %>
    </section>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/transactions/_transaction.html.erb
<tr>
<td>

<%= transaction.transaction_date %>
</td>
<td>
<%= transaction.payee.name %>
</td>
<td>
<%= transaction.category.name %>
</td>
<td>
<%= transaction.amount_in %>
</td>
<td>
<%= transaction.amount_out %>
</td>
<td></td>
<td></td>
</tr>

app/views/transactions/create.js.erb
$("#notice").html("<%= escape_javascript(notice) %>")
$("#transaction-table-container").html("<%= escape_javascript(render('accounts/transaction_table')) %>")

app/views/transactions/destroy.js.erb
$("#notice").html("<%= escape_javascript(notice) %>")

app/views/transactions/update.js.erb
$("#notice").html("<%= escape_javascript(notice) %>")